//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QTTabBarNative.rc
//

#define IDS_PROJNAME                    100
#define IDR_QTTABBARNATIVE              101
#define IDR_QTTABBARCLASS               102
#define IDR_AUTOLOADERNATIVE            103
#define IDR_QTSECONDVIEWBAR             104
#define IDR_QTDESKTOPTOOL               105
#define IDR_QTTABBAR_CONTEXT_MENU       200

#define IDS_OPTIONS_PAGE01_WINDOW       2000
#define IDS_OPTIONS_PAGE01_WINDOW_OTHERS 2001
#define IDS_OPTIONS_INVALID_LOCATION    2002
#define IDS_OPTIONS_WINDOW_AUTOHOOK     2003
#define IDS_OPTIONS_WINDOW_FAILMSG      2004
#define IDS_OPTIONS_WINDOW_CAPTURESEL   2005
#define IDS_OPTIONS_PAGE02_TABS         2006
#define IDS_OPTIONS_PAGE03_TWEAKS       2007

#define IDD_OPTIONS_DIALOG              300
#define IDD_OPTIONS_WINDOW              301
#define IDD_OPTIONS_TABS                302
#define IDD_OPTIONS_TWEAKS              303
#define IDD_OPTIONS_TOOLTIPS            304
#define IDD_OPTIONS_GENERAL             305
#define IDD_OPTIONS_APPEARANCE          306
#define IDD_OPTIONS_MOUSE               307
#define IDD_OPTIONS_KEYS                308
#define IDD_OPTIONS_GROUPS              309
#define IDD_OPTIONS_APPS                310
#define IDD_OPTIONS_BUTTONBAR           311
#define IDD_OPTIONS_PLUGINS             312
#define IDD_OPTIONS_LANGUAGE            313
#define IDD_OPTIONS_ABOUT               314

#define IDS_DESKTOPTOOL_TITLE           400
#define IDS_DESKTOPTOOL_GROUPS          401
#define IDS_DESKTOPTOOL_RECENT_TABS     402
#define IDS_DESKTOPTOOL_APPLICATIONS    403
#define IDS_DESKTOPTOOL_RECENT_FILES    404
#define IDS_DESKTOPTOOL_SETTINGS        405
#define IDS_DESKTOPTOOL_LOCK_MENU       406
#define IDS_DESKTOPTOOL_ONE_CLICK       407
#define IDS_DESKTOPTOOL_APP_SHORTCUTS   408
#define IDS_DESKTOPTOOL_INCLUDE         409
#define IDS_DESKTOPTOOL_EXPAND          410
#define IDS_DESKTOPTOOL_REORDER         411
#define IDS_DESKTOPTOOL_MOVE_UP         412
#define IDS_DESKTOPTOOL_MOVE_DOWN       413
#define IDS_DESKTOPTOOL_LOADING         414
#define IDS_DESKTOPTOOL_EMPTY           415
#define IDS_DESKTOPTOOL_NOT_AVAILABLE   416
#define IDS_DESKTOPTOOL_NO_TABBAR       417
#define IDS_CONTEXT_MENU_NEW_TAB        420
#define IDS_CONTEXT_MENU_CLOSE_TAB      421
#define IDS_CONTEXT_MENU_CLOSE_RIGHT    422
#define IDS_CONTEXT_MENU_CLOSE_LEFT     423
#define IDS_CONTEXT_MENU_CLOSE_OTHERS   424
#define IDS_CONTEXT_MENU_RESTORE_LAST   425
#define IDS_CONTEXT_MENU_ADD_TO_GROUP   426
#define IDS_CONTEXT_MENU_CREATE_GROUP   427
#define IDS_CONTEXT_MENU_LOCK_TAB       428
#define IDS_CONTEXT_MENU_UNLOCK_TAB     429
#define IDS_CONTEXT_MENU_CLONE_TAB      430
#define IDS_CONTEXT_MENU_OPEN_NEW_WIN   431
#define IDS_CONTEXT_MENU_COPY_PATH      432
#define IDS_CONTEXT_MENU_PROPERTIES     433
#define IDS_CONTEXT_MENU_HISTORY        434
#define IDS_CONTEXT_MENU_HISTORY_EMPTY  435
#define IDS_CONTEXT_MENU_HISTORY_CLEAR  436
#define IDS_CONTEXT_MENU_COMMAND        437
#define IDS_CONTEXT_MENU_EDIT_ALIAS     438
#define IDS_CONTEXT_MENU_REFRESH        439
#define IDS_CONTEXT_MENU_OPTIONS        440
#define IDS_CONTEXT_MENU_NO_GROUPS      441
#define IDS_CONTEXT_DIALOG_GROUP_TITLE  442
#define IDS_CONTEXT_DIALOG_GROUP_PROMPT 443
#define IDS_CONTEXT_DIALOG_ALIAS_TITLE  444
#define IDS_CONTEXT_DIALOG_ALIAS_PROMPT 445
#define IDS_CONTEXT_MENU_GROUP_CAPTION  446
#define IDS_BUTTONBAR_MENU_OVERFLOW     447

#define IDC_OPTIONS_TAB                 1000
#define IDC_APPLY_BUTTON                1001
#define IDC_RESET_BUTTON                1002
#define IDC_CAPTURE_NEW_WINDOWS         1100
#define IDC_CAPTURE_WECHAT_SELECTION    1101
#define IDC_RESTORE_SESSION             1102
#define IDC_RESTORE_ONLY_LOCKED         1103
#define IDC_CLOSE_BTN_UNLOCKED          1104
#define IDC_CLOSE_BTN_SINGLE            1105
#define IDC_TRAY_ON_CLOSE               1106
#define IDC_TRAY_ON_MINIMIZE            1107
#define IDC_AUTO_HOOK_WINDOW            1108
#define IDC_SHOW_FAIL_NAV_MSG           1109

#define IDC_WINDOW_HEADER               1200
#define IDC_WINDOW_SINGLE_LABEL         1201
#define IDC_DEFAULT_LOCATION_LABEL      1202
#define IDC_SESSION_LABEL               1203
#define IDC_CLOSE_BUTTON_LABEL          1204
#define IDC_TRAY_LABEL                  1205
#define IDC_WINDOW_OTHERS_LABEL         1206
#define IDC_TABS_HEADER                 1250
#define IDC_TABS_OPEN_LABEL             1251
#define IDC_TABS_NEW_TAB_COMBO          1252
#define IDC_TABS_CLOSE_SWITCH_LABEL     1253
#define IDC_TABS_CLOSE_SWITCH_COMBO     1254
#define IDC_TABS_ACTIVATE_NEW           1255
#define IDC_TABS_NEVER_OPEN_SAME        1256
#define IDC_TABS_RENAME_AMBIGUOUS       1257
#define IDC_TABS_DRAG_HOVER_LABEL       1258
#define IDC_TABS_DRAG_SWITCH            1259
#define IDC_TABS_DRAG_SUBMENU           1260
#define IDC_TABS_ICON_HEADER            1261
#define IDC_TABS_SHOW_FOLDER_ICONS      1262
#define IDC_TABS_SUBDIR_ICON_ACTION     1263
#define IDC_TABS_SHOW_DRIVE_LETTER      1264
#define IDC_TABS_CLOSE_HEADER           1265
#define IDC_TABS_CLOSE_BUTTONS          1266
#define IDC_TABS_CLOSE_ALT_ONLY         1267
#define IDC_TABS_CLOSE_HOVER_ONLY       1268
#define IDC_TABS_BAR_HEADER             1269
#define IDC_TABS_SHOW_NAV_BUTTONS       1270
#define IDC_TABS_NAV_LEFT               1271
#define IDC_TABS_NAV_RIGHT              1272
#define IDC_TABS_ALLOW_MULTI_ROWS       1273
#define IDC_TABS_ACTIVE_ROW_BOTTOM      1274
#define IDC_TABS_NEED_PLUS_BUTTON       1275
#define IDC_CAPTURE_ENABLE              1210
#define IDC_CAPTURE_DISABLE             1211
#define IDC_DEFAULT_LOCATION_EDIT       1212
#define IDC_DEFAULT_LOCATION_BROWSE     1213
#define IDC_SESSION_NEW                 1214
#define IDC_SESSION_RESTORE_ALL         1215
#define IDC_SESSION_RESTORE_LOCKED      1216
#define IDC_CLOSE_ACTION_WINDOW         1217
#define IDC_CLOSE_ACTION_TAB            1218
#define IDC_CLOSE_ACTION_UNLOCKED       1219
#define IDC_TWEAKS_HEADER               1300
#define IDC_TWEAKS_GENERAL_LABEL        1301
#define IDC_TWEAKS_ALWAYS_HEADERS       1302
#define IDC_TWEAKS_REDIRECT_LIBRARY     1303
#define IDC_TWEAKS_KILL_EXT             1304
#define IDC_TWEAKS_F2_SELECTION         1305
#define IDC_TWEAKS_WRAP_ARROW           1306
#define IDC_TWEAKS_BACKSPACE_UP         1307
#define IDC_TWEAKS_HORIZONTAL_SCROLL    1308
#define IDC_TWEAKS_OLD_LIST_LABEL       1309
#define IDC_TWEAKS_FORCE_SYSLISTVIEW    1310
#define IDC_TWEAKS_FULL_ROW_SELECT      1311
#define IDC_TWEAKS_GRID_LINES           1312
#define IDC_TWEAKS_ALT_ROW_COLORS       1313
#define IDC_TWEAKS_FOREGROUND_LABEL     1314
#define IDC_TWEAKS_FOREGROUND_VALUE     1315
#define IDC_TWEAKS_FOREGROUND_BUTTON    1316
#define IDC_TWEAKS_BACKGROUND_LABEL     1317
#define IDC_TWEAKS_BACKGROUND_VALUE     1318
#define IDC_TWEAKS_BACKGROUND_BUTTON    1319

#define ID_CONTEXT_NEWTAB               32768
#define ID_CONTEXT_CLOSETAB             32769
#define ID_CONTEXT_OPTIONS              32770
#define ID_CONTEXT_REFRESH              32771
#define ID_CONTEXT_RESTORELASTCLOSED    32772
#define ID_CONTEXT_CLOSE_RIGHT          32773
#define ID_CONTEXT_CLOSE_LEFT           32774
#define ID_CONTEXT_CLOSE_OTHERS         32775
#define ID_CONTEXT_ADD_TO_GROUP         32776
#define ID_CONTEXT_CREATE_GROUP         32777
#define ID_CONTEXT_TOGGLE_LOCK          32778
#define ID_CONTEXT_CLONE_TAB            32779
#define ID_CONTEXT_OPEN_NEW_WINDOW      32780
#define ID_CONTEXT_COPY_PATH            32781
#define ID_CONTEXT_TAB_ORDER            32782
#define ID_CONTEXT_PROPERTIES           32783
#define ID_CONTEXT_HISTORY_CLEAR        32784
#define ID_CONTEXT_OPEN_COMMAND         32785
#define ID_CONTEXT_EDIT_ALIAS           32786
#define ID_CONTEXT_GROUP_BASE           32800
#define ID_CONTEXT_HISTORY_BASE         32864
#define ID_CONTEXT_DYNAMIC_LAST         32927

#define ID_TIMER_SELECTTAB              1
#define ID_TIMER_CONTEXTMENU            2
#define ID_TIMER_SUBDIRTIP              3
#define WM_APP_UNSUBCLASS               (WM_APP + 1)

#define IDD_TEXT_INPUT                  400

#define IDC_TEXT_PROMPT                 1400
#define IDC_TEXT_INPUT                  1401

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define ID_BUTTONBAR_NAVIGATION_BACK    33000
#define ID_BUTTONBAR_NAVIGATION_FORWARD 33001
#define ID_BUTTONBAR_GROUPS             33002
#define ID_BUTTONBAR_RECENT_TABS        33003
#define ID_BUTTONBAR_APPLICATIONS       33004
#define ID_BUTTONBAR_NEW_WINDOW         33005
#define ID_BUTTONBAR_CLONE_TAB          33006
#define ID_BUTTONBAR_LOCK_TAB           33007
#define ID_BUTTONBAR_MISC_TOOLS         33008
#define ID_BUTTONBAR_TOPMOST            33009
#define ID_BUTTONBAR_CLOSE_TAB          33010
#define ID_BUTTONBAR_CLOSE_OTHERS       33011
#define ID_BUTTONBAR_CLOSE_WINDOW       33012
#define ID_BUTTONBAR_CLOSE_LEFT         33013
#define ID_BUTTONBAR_CLOSE_RIGHT        33014
#define ID_BUTTONBAR_GO_UP              33015
#define ID_BUTTONBAR_REFRESH            33016
#define ID_BUTTONBAR_SEARCH_FOCUS       33017
#define ID_BUTTONBAR_WINDOW_OPACITY     33018
#define ID_BUTTONBAR_FILTER_BAR         33019
#define ID_BUTTONBAR_OPTIONS            33020
#define ID_BUTTONBAR_RECENT_FILES       33021
#define ID_BUTTONBAR_PLUGINS            33022
#define ID_BUTTONBAR_DYNAMIC_FIRST      33100
#define ID_BUTTONBAR_DYNAMIC_LAST       33200

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         33201
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
