//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QTTabBarNative.rc
//

#define IDS_PROJNAME                    100
#define IDR_QTTABBARNATIVE              101
#define IDR_QTTABBARCLASS               102
#define IDR_AUTOLOADERNATIVE            103
#define IDR_QTSECONDVIEWBAR             104
#define IDR_QTDESKTOPTOOL               105
#define IDR_QTTABBAR_CONTEXT_MENU       200

#define IDS_OPTIONS_PAGE01_WINDOW       2000
#define IDS_OPTIONS_PAGE01_WINDOW_OTHERS 2001
#define IDS_OPTIONS_INVALID_LOCATION    2002
#define IDS_OPTIONS_WINDOW_AUTOHOOK     2003
#define IDS_OPTIONS_WINDOW_FAILMSG      2004
#define IDS_OPTIONS_WINDOW_CAPTURESEL   2005

#define IDD_OPTIONS_DIALOG              300
#define IDD_OPTIONS_WINDOW              301
#define IDD_OPTIONS_TABS                302
#define IDD_OPTIONS_TWEAKS              303
#define IDD_OPTIONS_TOOLTIPS            304
#define IDD_OPTIONS_GENERAL             305
#define IDD_OPTIONS_APPEARANCE          306
#define IDD_OPTIONS_MOUSE               307
#define IDD_OPTIONS_KEYS                308
#define IDD_OPTIONS_GROUPS              309
#define IDD_OPTIONS_APPS                310
#define IDD_OPTIONS_BUTTONBAR           311
#define IDD_OPTIONS_PLUGINS             312
#define IDD_OPTIONS_LANGUAGE            313
#define IDD_OPTIONS_ABOUT               314

#define IDS_DESKTOPTOOL_TITLE           400
#define IDS_DESKTOPTOOL_GROUPS          401
#define IDS_DESKTOPTOOL_RECENT_TABS     402
#define IDS_DESKTOPTOOL_APPLICATIONS    403
#define IDS_DESKTOPTOOL_RECENT_FILES    404
#define IDS_DESKTOPTOOL_SETTINGS        405
#define IDS_DESKTOPTOOL_LOCK_MENU       406
#define IDS_DESKTOPTOOL_ONE_CLICK       407
#define IDS_DESKTOPTOOL_APP_SHORTCUTS   408
#define IDS_DESKTOPTOOL_INCLUDE         409
#define IDS_DESKTOPTOOL_EXPAND          410
#define IDS_DESKTOPTOOL_REORDER         411
#define IDS_DESKTOPTOOL_MOVE_UP         412
#define IDS_DESKTOPTOOL_MOVE_DOWN       413
#define IDS_DESKTOPTOOL_LOADING         414
#define IDS_DESKTOPTOOL_EMPTY           415
#define IDS_DESKTOPTOOL_NOT_AVAILABLE   416
#define IDS_DESKTOPTOOL_NO_TABBAR       417

#define IDC_OPTIONS_TAB                 1000
#define IDC_APPLY_BUTTON                1001
#define IDC_RESET_BUTTON                1002
#define IDC_CAPTURE_NEW_WINDOWS         1100
#define IDC_CAPTURE_WECHAT_SELECTION    1101
#define IDC_RESTORE_SESSION             1102
#define IDC_RESTORE_ONLY_LOCKED         1103
#define IDC_CLOSE_BTN_UNLOCKED          1104
#define IDC_CLOSE_BTN_SINGLE            1105
#define IDC_TRAY_ON_CLOSE               1106
#define IDC_TRAY_ON_MINIMIZE            1107
#define IDC_AUTO_HOOK_WINDOW            1108
#define IDC_SHOW_FAIL_NAV_MSG           1109
#define IDC_NEED_PLUS_BUTTON            1110

#define IDC_WINDOW_HEADER               1200
#define IDC_WINDOW_SINGLE_LABEL         1201
#define IDC_DEFAULT_LOCATION_LABEL      1202
#define IDC_SESSION_LABEL               1203
#define IDC_CLOSE_BUTTON_LABEL          1204
#define IDC_TRAY_LABEL                  1205
#define IDC_WINDOW_OTHERS_LABEL         1206
#define IDC_CAPTURE_ENABLE              1210
#define IDC_CAPTURE_DISABLE             1211
#define IDC_DEFAULT_LOCATION_EDIT       1212
#define IDC_DEFAULT_LOCATION_BROWSE     1213
#define IDC_SESSION_NEW                 1214
#define IDC_SESSION_RESTORE_ALL         1215
#define IDC_SESSION_RESTORE_LOCKED      1216
#define IDC_CLOSE_ACTION_WINDOW         1217
#define IDC_CLOSE_ACTION_TAB            1218
#define IDC_CLOSE_ACTION_UNLOCKED       1219

#define ID_CONTEXT_NEWTAB               32768
#define ID_CONTEXT_CLOSETAB             32769
#define ID_CONTEXT_OPTIONS              32770
#define ID_CONTEXT_REFRESH              32771
#define ID_CONTEXT_RESTORELASTCLOSED    32772

#define ID_TIMER_SELECTTAB              1
#define ID_TIMER_CONTEXTMENU            2
#define WM_APP_UNSUBCLASS               (WM_APP + 1)

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define ID_BUTTONBAR_NAVIGATION_BACK    33000
#define ID_BUTTONBAR_NAVIGATION_FORWARD 33001
#define ID_BUTTONBAR_GROUPS             33002
#define ID_BUTTONBAR_RECENT_TABS        33003
#define ID_BUTTONBAR_APPLICATIONS       33004
#define ID_BUTTONBAR_NEW_WINDOW         33005
#define ID_BUTTONBAR_CLONE_TAB          33006
#define ID_BUTTONBAR_LOCK_TAB           33007
#define ID_BUTTONBAR_MISC_TOOLS         33008
#define ID_BUTTONBAR_TOPMOST            33009
#define ID_BUTTONBAR_CLOSE_TAB          33010
#define ID_BUTTONBAR_CLOSE_OTHERS       33011
#define ID_BUTTONBAR_CLOSE_WINDOW       33012
#define ID_BUTTONBAR_CLOSE_LEFT         33013
#define ID_BUTTONBAR_CLOSE_RIGHT        33014
#define ID_BUTTONBAR_GO_UP              33015
#define ID_BUTTONBAR_REFRESH            33016
#define ID_BUTTONBAR_SEARCH_FOCUS       33017
#define ID_BUTTONBAR_WINDOW_OPACITY     33018
#define ID_BUTTONBAR_FILTER_BAR         33019
#define ID_BUTTONBAR_OPTIONS            33020
#define ID_BUTTONBAR_RECENT_FILES       33021
#define ID_BUTTONBAR_PLUGINS            33022
#define ID_BUTTONBAR_DYNAMIC_FIRST      33100
#define ID_BUTTONBAR_DYNAMIC_LAST       33200

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         33201
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
